### ISSUE TITLE
Add 12 hour time 

### ISSUE THREAD

**Issue by tylerturdenpants** [n3d1117/n3d1117.github.io#1]
Right now the tweak only shows 24 time. Could we make it respect the system format?

**Comment by n3d1117** [comment]
Hi! For 12 hour time, just change [this line here](https://github.com/n3d1117/n3d1117.github.io/blob/1d94671d1a7716726568deb7b7eee634529c42a5/tweaks/Runaway/Tweak.xm#L180) to `hh:mm`. For one digit 12 hour time (e.g 5:32 instead of 05:32) use `h:mm`.

12 hour: [link to compiled .deb](https://www.dropbox.com/s/hmx9vj2wauxlh2k/it.ned.runaway_0.0.1_iphoneos-arm.deb?dl=0)
One digit 12 hour time: [link to compiled .deb](https://www.dropbox.com/s/5xjlest66ux8dil/it.ned.runaway_0.0.1_variant2_iphoneos-arm.deb?dl=0)
